    bond_style      hybrid harmonic
    angle_style     hybrid cosine/squared 
    #pair_style      hybrid lj/gromacs/coul/gromacs 9 12 0.000001 12  
    pair_style      hybrid lj/gromacs/coul/gromacs 9 12 0.000001 12
    special_bonds   lj/coul 0 1 1
    neigh_modify    every 5
    neighbor 4.0 bin
     dielectric      15
     pair_style      hybrid lj/gromacs/coul/gromacs 9 12 0.000001 12
     dielectric      15
     pair_style      hybrid lj/gromacs/coul/gromacs 9 12 0.000001 12
